const root=document.getElementById('app'),KEY='nc.admin.session.v1';
const state={session:loadSession(),page:'dashboard',sub:'pois',data:null,error:'',busy:false,modal:null,assistant:null};
const DEFAULT_SUB={content:'pois',activities:'membershipPlans',users:'users',settings:'staff'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadSession(){try{const s=JSON.parse(sessionStorage.getItem(KEY)||'null');return s?.expiresAt>Date.now()&&s.user?.audience==='admin'?s:null;}catch{return null;}}
async function api(path,{method='GET',data,token=state.session?.token}={}){const r=await fetch('/api/v1'+path,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined});let v;try{v=await r.json();}catch{throw new Error('服务返回格式错误');}if(!r.ok)throw new Error(v.error?.message||'请求失败');return v;}
function setError(e){state.error=e instanceof Error?e.message:String(e);render();}
function title(x){return x?.data?.name||x?.data?.title||x?.name||x?.title||x?.phoneMasked||x?.phone_mask||x?.id||'未命名';}
const dt=v=>v?new Date(Number(v)||v).toLocaleString('zh-CN',{hour12:false}):'—';
function nav(page){if(state.page!==page&&DEFAULT_SUB[page])state.sub=DEFAULT_SUB[page];state.page=page;state.modal=null;state.error='';location.hash=page;load();}
async function load(){if(!state.session)return render();state.busy=true;render();try{if(state.page==='dashboard')state.data=await api('/admin/content/counts');else if(state.page==='content'){if(state.sub==='home')state.data=await api('/admin/content/home');else if(state.sub==='media')state.data=await api('/admin/media');else if(state.sub==='discovery'){const [status,candidates,nodes]=await Promise.all([api('/admin/discovery/status'),api('/admin/discovery/candidates'),api('/admin/content/nodes')]);state.data={status,candidates:candidates.items||[],nodes:nodes.items||[]};}else state.data=await api('/admin/content/'+state.sub);}else if(state.page==='activities')state.data=await api('/admin/content/'+state.sub);else if(state.page==='users'){if(state.sub==='users')state.data=await api('/admin/users');else if(state.sub==='tickets')state.data=await api('/admin/tickets');else state.data=await api('/admin/messages');}else if(state.page==='settings'){if(state.sub==='staff')state.data=await api('/admin/staff');else{const [status,history]=await Promise.all([api('/admin/integrations'),api('/admin/integration-verifications')]);state.data={status,history:history.items||[]};}}}catch(e){state.error=e.message;}finally{state.busy=false;render();}}
function navHtml(){const item=(key,label)=>`<button data-nav="${key}" class="${state.page===key?'active':''}">${label}</button>`;return `<div class="brand">南充城市漫游<small>运营工作台 · 统一后端</small></div><div class="nav">${item('dashboard','工作台')}${item('content','内容管理')}${item('activities','活动与权益')}${item('users','用户与服务')}<div class="settings">${item('settings','设置')}</div></div><footer>三个前端共用 /api/v1<br>修改需显式发布</footer>`;}
function topHtml(){return `<header class="top"><button class="mobile btn" id="menu">菜单</button><b>${({dashboard:'工作台',content:'内容管理',activities:'活动与权益',users:'用户与服务',settings:'设置'})[state.page]}</b><div class="account">${esc(state.session.user.phoneMasked||'管理员')} · ${esc(state.session.user.role)} <button class="btn" id="logout">退出</button></div></header>`;}
function tabs(items){return `<div class="tabs">${items.map(([k,v])=>`<button data-sub="${k}" class="${state.sub===k?'active':''}">${v}</button>`).join('')}</div>`;}
function dashboard(){const d=state.data||{};return `<div class="page-head"><div><h1>今天需要处理什么</h1><p>内容、用户与发布使用同一数据库。</p></div><button class="btn primary" id="publish">发布当前内容</button></div><div class="grid">${[['pois','地点'],['nodes','站点'],['walks','攻略'],['steps','攻略步骤']].map(([k,l])=>`<div class="metric"><span>${l}</span><strong>${d[k]??'—'}</strong><small>统一内容库</small></div>`).join('')}</div><section class="panel"><h2>常用操作</h2><div class="actions" style="justify-content:flex-start"><button class="btn" data-nav="content">管理地点与攻略</button><button class="btn" data-nav="activities">配置活动与权益</button><button class="btn" data-nav="users">处理用户反馈</button><button class="btn" id="ai-open">AI运营助手</button></div></section>`;}
function rowsOf(){return state.data?.items||[];}
function contentPage(){const tabsList=[['home','首页'],['nodes','站点'],['pois','地点'],['walks','攻略'],['media','媒体素材'],['discovery','POI采集'],['banners','Banner'],['announcements','公告']];const body=state.sub==='home'?homeCard():state.sub==='media'?mediaPage():state.sub==='discovery'?discoveryPage():recordsTable(rowsOf(),true);return `<div class="page-head"><div><h1>内容管理</h1><p>编辑现有内容，保存后仍需发布才会影响 H5 与小程序。</p></div><button class="btn primary" data-publish>发布当前内容</button></div>${tabs(tabsList)}<section class="panel">${body}</section>`;}
function activities(){return `<div class="page-head"><div><h1>活动与权益</h1><p>会员、权益和活动均来自统一发布内容。</p></div></div>${tabs([['membershipPlans','会员方案'],['benefits','权益'],['events','活动']])}<section class="panel">${recordsTable(rowsOf(),true)}</section>`;}
function usersPage(){const main=state.sub==='users'?usersTable():state.sub==='tickets'?ticketsTable():messagesTable();return `<div class="page-head"><div><h1>用户与服务</h1><p>用户详情中集中查看会员、权益、报名、反馈和消息。</p></div></div>${tabs([['users','用户档案'],['tickets','客服工单'],['messages','消息记录']])}<section class="panel">${main}</section>`;}
function settingsPage(){return `<div class="page-head"><div><h1>设置</h1><p>低频系统配置独立放置。</p></div></div>${tabs([['staff','人员权限'],['integrations','接口验收']])}<section class="panel">${state.sub==='staff'?staffTable():integrationsPage()}</section>`;}
function recordsTable(rows,editable){if(!rows.length)return '<div class="empty">暂无记录</div>';return `<div class="table-wrap"><table><thead><tr><th>内容</th><th>状态</th><th>版本</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(title(r))}</b><small>${esc(r.id)}</small></td><td>${esc(r.status||'active')}</td><td>V${esc(r.revision||1)}</td><td>${editable?`<button class="btn" data-edit="${esc(r.id)}">编辑</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;}
function homeCard(){const r=state.data;if(!r)return '<div class="empty">首页配置尚未初始化</div>';return `<h2>${esc(r.data?.title||'首页配置')}</h2><p>${esc(r.data?.heroTitle||'')}</p><button class="btn" data-edit="home">编辑首页</button>`;}
function usersTable(){const rows=rowsOf();if(!rows.length)return '<div class="empty">暂无用户记录</div>';return `<div class="table-wrap"><table><thead><tr><th>用户</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.phoneMask||r.phone_mask||'未绑定手机号')}</b><small>${esc(r.id)}</small></td><td>${esc(r.status)}</td><td>${dt(r.createdAt||r.created_at)}</td><td><button class="btn" data-user="${esc(r.id)}">查看档案</button></td></tr>`).join('')}</tbody></table></div>`;}
function ticketsTable(){const rows=rowsOf();if(!rows.length)return '<div class="empty">暂无客服工单</div>';return `<div class="table-wrap"><table><thead><tr><th>用户</th><th>类型</th><th>问题</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.phoneMasked||'')}</td><td>${esc(r.kind)} · ${esc(r.category)}</td><td>${esc(r.description)}</td><td>${esc(r.status)}</td><td><button class="btn" data-ticket="${esc(r.id)}">处理</button></td></tr>`).join('')}</tbody></table></div>`;}
function messagesTable(){const rows=rowsOf();if(!rows.length)return '<div class="empty">暂无站内消息</div>';return `<div class="table-wrap"><table><thead><tr><th>用户</th><th>标题</th><th>状态</th><th>时间</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.phoneMasked||'')}</td><td><b>${esc(r.title)}</b><small>${esc(r.body)}</small></td><td>${r.readAt?'已读':'未读'}</td><td>${dt(r.createdAt)}</td></tr>`).join('')}</tbody></table></div>`;}
function staffTable(){const rows=rowsOf();return `<div class="toolbar"><span>只有管理员可修改工作人员角色</span><button class="btn primary" id="staff-add">授权用户</button></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>账号</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.phoneMasked||r.userId)}<small>${esc(r.userId)}</small></td><td>${esc(r.role)}</td><td>${r.enabled?'启用':'停用'}</td><td><button class="btn" data-staff="${esc(r.userId)}">修改</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">暂无额外工作人员</div>'}`;}
function badge(value){return `<span class="status status-${esc(value)}">${esc(value)}</span>`;}
function mediaPage(){const rows=rowsOf();if(!rows.length)return '<div class="empty">暂无媒体素材。旧图片必须先完成来源、版权与地点匹配核验后才能进入正式发布。</div>';return `<div class="toolbar"><span>素材必须同时满足：版权/授权已确认、地点匹配已确认、图片已入本地内容寻址库。</span></div><div class="media-grid">${rows.map(r=>`<article class="media-card"><div class="media-preview">${r.url?`<img src="${esc(r.url)}" alt="${esc(r.id)}">`:'<div class="media-placeholder">暂无预览</div>'}</div><div class="media-body"><b>${esc(r.id)}</b><small>${r.storagePath?'已入库 · '+esc(r.storagePath.slice(0,12)):'外部来源候选，未入库'}</small><div class="status-row">版权 ${badge(r.rightsStatus)} 地点 ${badge(r.matchStatus)}</div><small>使用：${r.usage?.length?r.usage.map(x=>esc(x.name)).join('、'):'未关联地点'}</small><div class="actions"><button class="btn" data-media-review="${esc(r.id)}">审核</button><button class="btn primary" data-media-assign="${esc(r.id)}" ${r.storagePath&&r.rightsStatus==='confirmed'&&r.matchStatus==='confirmed'?'':'disabled'}>设为地点封面</button></div></div></article>`).join('')}</div>`;}
function discoveryPage(){const d=state.data||{},rows=d.candidates||[],nodes=d.nodes||[];return `<div class="toolbar"><span>${d.status?.configured?'高德 POI 2.0 已配置，可自动采集候选。':'POI服务未配置；配置服务端 AMAP_SERVER_KEY 后才能采集。'} 自动结果永不直接发布。</span></div><form id="discovery-form" class="form-grid"><label><span>所属站点</span><select name="nodeId" required><option value="">请选择</option>${nodes.map(x=>`<option value="${esc(x.id)}">${esc(title(x))}</option>`).join('')}</select></label><label><span>关键词</span><input name="keywords" placeholder="例如 咖啡 / 火锅 / 亲子"></label><label><span>中心经度（GCJ02）</span><input name="longitude" inputmode="decimal" placeholder="站点暂无坐标时必填"></label><label><span>中心纬度（GCJ02）</span><input name="latitude" inputmode="decimal" placeholder="站点暂无坐标时必填"></label><label><span>半径（米）</span><input name="radius" type="number" value="3000" min="100" max="50000"></label><div class="actions"><button class="btn primary" ${d.status?.configured?'':'disabled'}>采集到候选池</button></div></form><hr class="sep"><h3>候选池 · ${rows.length}</h3>${rows.length?`<div class="table-wrap"><table><thead><tr><th>地点</th><th>来源</th><th>距离</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.name)}</b><small>${esc(r.address||'')}</small></td><td>${esc(r.provider)}<small>${esc(r.providerCategory||'')}</small></td><td>${r.distanceM??'—'}m</td><td>${badge(r.status)}${r.mappedCategory?`<small>${esc(r.mappedCategory)}</small>`:''}</td><td>${r.status==='pending_review'?`<button class="btn" data-candidate-review="${esc(r.id)}">人工审核</button>`:''}${r.status==='approved'?`<button class="btn primary" data-candidate-import="${esc(r.id)}">导入地点草稿</button>`:''}${r.status==='imported'?`<span>已导入 ${esc(r.importedPoiId||'')}</span>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">尚无候选。自动采集只负责发现，人工审核决定是否进入草稿。</div>'}`;}
function integrationsPage(){const d=state.data||{},s=d.status||{},rows=d.history||[];const card=(name,configured,detail,action)=>`<article class="integration-card"><div><b>${name}</b><small>${esc(detail)}</small></div><div>${configured?badge('configured'):badge('blocked')}</div>${action||''}</article>`;return `<div class="integration-grid">${card('AI模型',s.ai?.configured, s.ai?.configured?`${s.ai.provider} / ${s.ai.model}`:'服务端模型密钥未配置',`<button class="btn" id="verify-ai" ${s.ai?.configured?'':'disabled'}>真实调用验证</button>`)}${card('微信服务端',s.wechat?.configured,s.wechat?.configured?'AppID …'+esc(s.wechat.appidSuffix||''):'AppID/AppSecret 未配置',`<button class="btn" id="verify-wechat" ${s.wechat?.configured?'':'disabled'}>官方接口验证</button>`)}${card('正式短信',s.sms?.configured,s.sms?.configured?esc(s.sms.provider||'已配置'):'短信网关未配置',`<button class="btn" id="verify-sms" ${s.sms?.configured?'':'disabled'}>发送并收码验证</button>`)}${card('POI自动采集',s.poiDiscovery?.configured,'高德 POI 2.0 · 候选池模式','')}${card('IVY Bus',!(s.ivy?.missing||[]).length,(s.ivy?.missing||[]).length?'缺少：'+(s.ivy.missing||[]).join('、'):'配置字段已齐；仍需供应商现场验收','')}</div><h3>最近验收记录</h3>${rows.length?`<div class="table-wrap"><table><thead><tr><th>集成</th><th>状态</th><th>结果</th><th>时间</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.integration)}<small>${esc(r.provider||'')}</small></td><td>${badge(r.status)}</td><td><small>${esc(JSON.stringify(r.detail||{}))}</small></td><td>${dt(r.createdAt)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">尚无真实外部验收记录</div>'}`;}

function modalHtml(){
  if(!state.modal)return'';const m=state.modal;
  if(m.type==='edit'){const d=m.row.data||{};return `<div class="modal-mask"><section class="modal"><header><h2>编辑 ${esc(title(m.row))}</h2><button class="btn" data-close>关闭</button></header><form id="edit-form"><div class="form-grid">${[['name','名称'],['title','标题'],['description','介绍'],['address','地址'],['category','类别'],['subtitle','副标题']].filter(([k])=>k in d).map(([k,l])=>`<label class="${k==='description'?'full':''}"><span>${l}</span>${k==='description'?`<textarea name="${k}">${esc(d[k])}</textarea>`:`<input name="${k}" value="${esc(d[k])}">`}</label>`).join('')}<label class="full"><span>高级 JSON（保留全部现有字段）</span><textarea name="json" style="min-height:220px">${esc(JSON.stringify(d,null,2))}</textarea></label></div><div class="actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存草稿</button></div></form></section></div>`;}
  if(m.type==='user'){const p=m.profile;return `<div class="modal-mask"><section class="modal"><header><h2>用户档案</h2><button class="btn" data-close>关闭</button></header><p>${esc(p.user.phoneMasked||p.user.id)}</p>${[['会员',p.memberships],['权益',p.grants],['活动报名',p.registrations],['服务记录',[...p.tickets,...p.privacyRequests]],['消息',p.messages]].map(([l,v])=>`<h3>${l} · ${v.length}</h3><div class="detail-list">${v.length?v.map(x=>`<article><h3>${esc(x.title||x.description||x.id)}</h3><small>${esc(x.status||'')}</small></article>`).join(''):'<p>暂无</p>'}</div>`).join('')}</section></div>`;}
  if(m.type==='ticket'){const r=m.row;return `<div class="modal-mask"><section class="modal"><header><h2>处理客服工单</h2><button class="btn" data-close>关闭</button></header><p>${esc(r.description)}</p><form id="ticket-form"><label>状态<select name="status">${['open','processing','waiting','resolved','closed'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>对用户回复<textarea name="publicReply">${esc(r.public_reply||'')}</textarea></label><label>内部备注（不会返回用户）<textarea name="internalNote">${esc(r.internal_note||'')}</textarea></label><div class="actions"><button class="btn primary">保存处理结果</button></div></form></section></div>`;}
  if(m.type==='staff'){return `<div class="modal-mask"><section class="modal"><header><h2>工作人员权限</h2><button class="btn" data-close>关闭</button></header><form id="staff-form"><label>用户ID<input name="userId" value="${esc(m.row?.userId||'')}"></label><label>角色<select name="role">${['publisher','operator','customer_service','viewer'].map(s=>`<option ${m.row?.role===s?'selected':''}>${s}</option>`).join('')}</select></label><label><input name="enabled" type="checkbox" ${m.row?.enabled!==false?'checked':''}> 启用后台访问</label><div class="actions"><button class="btn primary">保存权限</button></div></form></section></div>`;}
  if(m.type==='assistant'){const a=m.data||{};return `<div class="modal-mask"><section class="modal"><header><h2>AI 运营助手</h2><button class="btn" data-close>关闭</button></header><p class="notice">AI只能查询真实业务数据并生成待确认提案；不会自动发布。</p><p>模型状态：${a.status?.configured?'已配置 · '+esc(a.status.provider)+' / '+esc(a.status.model):'未配置服务端模型'}</p><form id="ai-form"><label>运营任务<textarea name="message" placeholder="例如：查询哪些地点缺图片；或优化清晖阁介绍，只生成提案"></textarea></label><button class="btn primary" ${a.status?.configured?'':'disabled'}>执行任务</button></form>${a.result?`<h3>结果</h3><p style="white-space:pre-wrap">${esc(a.result.text)}</p>${(a.result.proposals||[]).map(p=>`<article class="panel"><b>${esc(p.kind)} · 待确认提案</b><pre>${esc(JSON.stringify({before:p.before,patch:p.patch},null,2))}</pre><button class="btn primary" data-proposal="${esc(p.id)}">确认保存草稿</button></article>`).join('')}`:''}</section></div>`;}
  if(m.type==='mediaReview'){const r=m.row,e=r.evidence||{};return `<div class="modal-mask"><section class="modal"><header><h2>素材审核 · ${esc(r.id)}</h2><button class="btn" data-close>关闭</button></header><div class="media-preview modal-preview">${r.url?`<img src="${esc(r.url)}" alt="素材预览">`:'<div class="media-placeholder">暂无预览</div>'}</div><form id="media-review-form" class="form-grid"><label><span>版权/授权状态</span><select name="rightsStatus">${['inherited_unverified','pending','confirmed','rejected'].map(x=>`<option ${r.rightsStatus===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>地点匹配状态</span><select name="matchStatus">${['inherited_unverified','pending','confirmed','rejected'].map(x=>`<option ${r.matchStatus===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full"><span>授权/来源依据</span><textarea name="rightsEvidence">${esc(e.rightsEvidence||'')}</textarea></label><label class="full"><span>地点匹配核对依据</span><textarea name="matchEvidence">${esc(e.matchEvidence||'')}</textarea></label><label class="full"><span>备注</span><textarea name="note">${esc(e.note||'')}</textarea></label><div class="actions full"><button class="btn primary">保存审核</button></div></form></section></div>`;}
  if(m.type==='mediaAssign'){const r=m.row,pois=m.pois||[];return `<div class="modal-mask"><section class="modal"><header><h2>设为地点封面</h2><button class="btn" data-close>关闭</button></header><p class="notice">此操作只写入内容草稿；游客端仍需显式发布才会变化。</p><form id="media-assign-form"><label>地点<select name="poiId" required><option value="">请选择地点</option>${pois.map(x=>`<option value="${esc(x.id)}">${esc(title(x))}</option>`).join('')}</select></label><label>图片说明<input name="imageLabel" value="场地实景"></label><div class="actions"><button class="btn primary">保存为地点封面草稿</button></div></form></section></div>`;}
  if(m.type==='candidateReview'){const r=m.row;return `<div class="modal-mask"><section class="modal"><header><h2>审核 POI 候选</h2><button class="btn" data-close>关闭</button></header><h3>${esc(r.name)}</h3><p>${esc(r.address||'')}</p><small>${esc(r.providerCategory||'')}</small><form id="candidate-review-form"><label>游客端分类<select name="mappedCategory">${['吃什么','喝什么','看什么','玩什么','休息'].map(x=>`<option ${r.mappedCategory===x?'selected':''}>${x}</option>`).join('')}</select></label><label>游客端介绍草稿<textarea name="descriptionDraft">${esc(r.descriptionDraft||'')}</textarea></label><label>审核备注<textarea name="reviewNote">${esc(r.reviewNote||'')}</textarea></label><div class="actions"><button type="button" class="btn danger" id="candidate-reject">拒绝</button><button class="btn primary">审核通过</button></div></form></section></div>`;}
  if(m.type==='smsVerify'){const d=m.data||{};return `<div class="modal-mask"><section class="modal"><header><h2>正式短信送达验收</h2><button class="btn" data-close>关闭</button></header><p class="notice">第一步真实发送；第二步必须输入手机实际收到的验证码。只有两步都完成，系统才记录“送达验证通过”。</p>${!d.challengeId?`<form id="sms-start-form"><label>验收手机号<input name="phone" inputmode="tel" maxlength="11" placeholder="输入现场可收短信的手机号" required></label><div class="actions"><button class="btn primary">发送验收短信</button></div></form>`:`<p>已发送至 ${esc(d.phoneMasked)}，请填写手机实际收到的验证码。</p><form id="sms-confirm-form"><label>收到的6位验证码<input name="code" inputmode="numeric" maxlength="6" required></label><div class="actions"><button class="btn primary">确认实际送达</button></div></form>`}</section></div>`;}
  return'';
}
function render(){if(!state.session)return renderLogin();const body=state.page==='dashboard'?dashboard():state.page==='content'?contentPage():state.page==='activities'?activities():state.page==='users'?usersPage():settingsPage();root.innerHTML=`<div class="shell"><aside class="sidebar" id="side">${navHtml()}</aside><main class="main">${topHtml()}<div class="content">${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}${state.busy?'<div class="notice">正在读取真实数据…</div>':''}${body}</div></main>${modalHtml()}</div>`;bind();}
function renderLogin(){root.innerHTML=`<div class="login"><section class="login-card"><h1>运营工作台</h1><p>手机号 + 验证码登录。只有已授权工作人员可以进入。</p>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}<form id="login-form"><label>手机号<input name="phone" inputmode="tel" maxlength="11" required></label><label>验证码<div style="display:flex;gap:8px"><input name="code" inputmode="numeric" maxlength="6"><button class="btn" type="button" id="get-code">获取验证码</button></div></label><div class="code" id="code-hint"></div><button class="btn primary">进入后台</button></form></section></div>`;bindLogin();}
function bindLogin(){const form=document.getElementById('login-form');document.getElementById('get-code').onclick=async()=>{try{state.error='';const phone=form.phone.value;const r=await api('/auth/challenge',{method:'POST',data:{phone,audience:'admin'},token:null});form.dataset.challenge=JSON.stringify(r);document.getElementById('code-hint').textContent=r.debugCode?'测试验证码：'+r.debugCode:'验证码已发送';}catch(e){setError(e);}};form.onsubmit=async e=>{e.preventDefault();try{const c=JSON.parse(form.dataset.challenge||'null');if(!c)throw new Error('请先获取验证码');const r=await api('/auth/verify',{method:'POST',data:{challengeId:c.challengeId,phoneHash:c.phoneHash,code:form.code.value,clientType:'admin'},token:null});if(r.user.audience!=='admin')throw new Error('不是后台会话');sessionStorage.setItem(KEY,JSON.stringify(r));state.session=r;state.page='dashboard';state.error='';load();}catch(x){setError(x);}};}
function bind(){
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
  document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{state.sub=b.dataset.sub;state.modal=null;load();});
  document.getElementById('logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST',data:{},token:state.session.token});}finally{sessionStorage.removeItem(KEY);state.session=null;render();}};
  document.getElementById('menu')?.addEventListener('click',()=>document.getElementById('side').classList.toggle('open'));
  document.querySelectorAll('#publish,[data-publish]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('确认将当前内容草稿发布到 H5 和小程序？'))return;try{const r=await api('/admin/content/publish',{method:'POST',data:{}});alert('已发布版本 '+r.version);load();}catch(e){setError(e);}}));
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{try{const r=state.sub==='home'?state.data:await api('/admin/content/'+state.sub+'/'+b.dataset.edit);state.modal={type:'edit',row:r};render();}catch(e){setError(e);}});
  document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{try{state.modal={type:'user',profile:await api('/admin/users/'+b.dataset.user)};render();}catch(e){setError(e);}});
  document.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>{state.modal={type:'ticket',row:rowsOf().find(x=>x.id===b.dataset.ticket)};render();});
  document.getElementById('staff-add')?.addEventListener('click',()=>{state.modal={type:'staff',row:null};render();});
  document.getElementById('ai-open')?.addEventListener('click',async()=>{try{state.modal={type:'assistant',data:{status:await api('/admin/assistant/status')}};render();}catch(e){setError(e);}});
  document.querySelectorAll('[data-staff]').forEach(b=>b.onclick=()=>{state.modal={type:'staff',row:rowsOf().find(x=>x.userId===b.dataset.staff)};render();});
  document.querySelectorAll('[data-media-review]').forEach(b=>b.onclick=()=>{state.modal={type:'mediaReview',row:rowsOf().find(x=>x.id===b.dataset.mediaReview)};render();});
  document.querySelectorAll('[data-media-assign]').forEach(b=>b.onclick=async()=>{try{const pois=await api('/admin/content/pois');state.modal={type:'mediaAssign',row:rowsOf().find(x=>x.id===b.dataset.mediaAssign),pois:pois.items||[]};render();}catch(e){setError(e);}});
  document.querySelectorAll('[data-candidate-review]').forEach(b=>b.onclick=()=>{state.modal={type:'candidateReview',row:(state.data?.candidates||[]).find(x=>x.id===b.dataset.candidateReview)};render();});
  document.querySelectorAll('[data-candidate-import]').forEach(b=>b.onclick=async()=>{if(!confirm('确认将该候选导入地点草稿？导入后仍不会自动发布。'))return;try{const r=await api('/admin/discovery/candidates/'+b.dataset.candidateImport+'/import',{method:'POST',data:{}});alert('已导入地点草稿 '+r.poiId+'，尚未发布');await load();}catch(e){setError(e);}});
  document.getElementById('verify-ai')?.addEventListener('click',async()=>{try{const r=await api('/admin/integrations/verify/ai',{method:'POST',data:{}});alert('AI真实调用验证：'+r.status);await load();}catch(e){setError(e);}});
  document.getElementById('verify-wechat')?.addEventListener('click',async()=>{try{const r=await api('/admin/integrations/verify/wechat',{method:'POST',data:{}});alert('微信官方接口验证：'+r.status);await load();}catch(e){setError(e);}});
  document.getElementById('verify-sms')?.addEventListener('click',()=>{state.modal={type:'smsVerify',data:{}};render();});
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{state.modal=null;render();});
  const discovery=document.getElementById('discovery-form');if(discovery)discovery.onsubmit=async e=>{e.preventDefault();try{const data={nodeId:discovery.nodeId.value,keywords:discovery.keywords.value,radius:Number(discovery.radius.value||3000)};if(discovery.longitude.value)data.longitude=Number(discovery.longitude.value);if(discovery.latitude.value)data.latitude=Number(discovery.latitude.value);const r=await api('/admin/discovery/run',{method:'POST',data});alert('已写入候选池 '+r.upserted+' 条；未自动发布');await load();}catch(x){setError(x);}};
  const ef=document.getElementById('edit-form');if(ef)ef.onsubmit=async e=>{e.preventDefault();try{const advanced=JSON.parse(ef.json.value);for(const el of ef.elements)if(el.name&&el.name!=='json'&&el.value!=='')advanced[el.name]=el.value;const m=state.modal.row;await api(state.sub==='home'?'/admin/content/home':'/admin/content/'+state.sub+'/'+m.id,{method:'POST',data:{expectedRevision:m.revision,data:advanced}});state.modal=null;await load();}catch(x){setError(x);}};
  const tf=document.getElementById('ticket-form');if(tf)tf.onsubmit=async e=>{e.preventDefault();try{const m=state.modal.row;await api('/admin/tickets/'+m.id,{method:'POST',data:{status:tf.status.value,publicReply:tf.publicReply.value,internalNote:tf.internalNote.value}});state.modal=null;await load();}catch(x){setError(x);}};
  const sf=document.getElementById('staff-form');if(sf)sf.onsubmit=async e=>{e.preventDefault();try{await api('/admin/staff',{method:'POST',data:{userId:sf.userId.value,role:sf.role.value,enabled:sf.enabled.checked}});state.modal=null;await load();}catch(x){setError(x);}};
  const af=document.getElementById('ai-form');if(af)af.onsubmit=async e=>{e.preventDefault();try{const result=await api('/admin/assistant/ask',{method:'POST',data:{message:af.message.value}});state.modal={type:'assistant',data:{...state.modal.data,result}};render();}catch(x){setError(x);}};
  document.querySelectorAll('[data-proposal]').forEach(b=>b.onclick=async()=>{if(!confirm('确认将AI提案保存为业务草稿？不会自动发布。'))return;try{await api('/admin/assistant/proposals/'+b.dataset.proposal+'/apply',{method:'POST',data:{confirmed:true}});alert('AI提案已保存为草稿，尚未发布');state.modal=null;await load();}catch(x){setError(x);}});
  const mf=document.getElementById('media-review-form');if(mf)mf.onsubmit=async e=>{e.preventDefault();try{const m=state.modal.row;await api('/admin/media/'+m.id+'/review',{method:'POST',data:{rightsStatus:mf.rightsStatus.value,matchStatus:mf.matchStatus.value,rightsEvidence:mf.rightsEvidence.value,matchEvidence:mf.matchEvidence.value,note:mf.note.value}});state.modal=null;await load();}catch(x){setError(x);}};
  const ma=document.getElementById('media-assign-form');if(ma)ma.onsubmit=async e=>{e.preventDefault();try{const m=state.modal.row;await api('/admin/media/'+m.id+'/assign',{method:'POST',data:{poiId:ma.poiId.value,imageLabel:ma.imageLabel.value}});alert('已保存为地点封面草稿，尚未发布');state.modal=null;await load();}catch(x){setError(x);}};
  const cr=document.getElementById('candidate-review-form');if(cr){cr.onsubmit=async e=>{e.preventDefault();try{const m=state.modal.row;await api('/admin/discovery/candidates/'+m.id+'/review',{method:'POST',data:{decision:'approve',mappedCategory:cr.mappedCategory.value,descriptionDraft:cr.descriptionDraft.value,reviewNote:cr.reviewNote.value}});state.modal=null;await load();}catch(x){setError(x);}};document.getElementById('candidate-reject').onclick=async()=>{try{const m=state.modal.row;await api('/admin/discovery/candidates/'+m.id+'/review',{method:'POST',data:{decision:'reject',reviewNote:cr.reviewNote.value}});state.modal=null;await load();}catch(x){setError(x);}};}
  const ss=document.getElementById('sms-start-form');if(ss)ss.onsubmit=async e=>{e.preventDefault();try{const r=await api('/admin/integrations/verify/sms/start',{method:'POST',data:{phone:ss.phone.value}});state.modal={type:'smsVerify',data:r};render();}catch(x){setError(x);}};
  const sc=document.getElementById('sms-confirm-form');if(sc)sc.onsubmit=async e=>{e.preventDefault();try{const d=state.modal.data,r=await api('/admin/integrations/verify/sms/confirm',{method:'POST',data:{challengeId:d.challengeId,code:sc.code.value}});alert('短信实际送达验证：'+r.status);state.modal=null;await load();}catch(x){setError(x);}};
}
const initial=location.hash.slice(1);if(['dashboard','content','activities','users','settings'].includes(initial))state.page=initial;if(state.page==='activities')state.sub='membershipPlans';if(state.page==='users')state.sub='users';if(state.page==='settings')state.sub='staff';window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(['dashboard','content','activities','users','settings'].includes(p)){state.page=p;load();}});render();if(state.session)load();
