export const kinds=['events','banners','announcements','membershipPlans','benefits'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const schemas={
 events:[['title','活动标题'],['description','活动介绍','textarea'],['rules','报名规则','textarea'],['address','活动地点'],['registration','报名方式',['free','closed']],['capacity','名额（0 不限）','number'],['startsAt','报名开始时间','datetime-local'],['endsAt','报名结束时间','datetime-local']],
 banners:[['title','Banner 标题'],['subtitle','副标题'],['targetType','跳转类型',['event','benefit','walk','poi','station','guide']]],
 announcements:[['title','公告标题'],['body','公告内容','textarea']],
 membershipPlans:[['name','会员名称'],['description','会员介绍','textarea'],['terms','会员规则','textarea'],['validDays','有效天数（0 长期）','number']],
 benefits:[['name','权益名称'],['description','权益介绍','textarea'],['rules','领取规则','textarea'],['provider','提供方'],['digitalContent','使用说明','textarea'],['capacity','名额（0 不限）','number'],['validDays','有效天数（0 长期）','number']]
};
export function editor(kind,row,media,targets){
 const d=row?.data||{},field=([key,label,type='text'])=>`<label><span>${label}</span>${Array.isArray(type)?`<select name="${key}">${type.map(v=>`<option value="${v}" ${d[key]===v?'selected':''}>${({free:'免费报名',closed:'关闭报名',event:'活动',benefit:'权益',walk:'攻略',poi:'地点',station:'站点',guide:'乘车指南'})[v]||v}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}">${esc(d[key])}</textarea>`:`<input name="${key}" type="${type}" ${['name','title'].includes(key)?'required maxlength="200"':''} ${type==='number'?'min="0" step="1"':''} value="${esc(type==='datetime-local'&&d[key]?localTime(d[key]):d[key]??(type==='number'?0:''))}">`}</label>`;
 return `<div class="modal-mask"><section class="modal"><header><h2>${row?'编辑':'新建'}运营内容</h2><button class="btn" data-close>关闭</button></header><form id="operational-form"><div class="form-grid">${schemas[kind].map(field).join('')}${kind==='banners'?`<label>跳转目标<select name="targetId"><option value="">乘车指南无需目标</option>${targets.map(x=>`<option data-kind="${x.kind}" value="${esc(x.id)}" ${d.targetId===x.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label>`:''}<label>封面图片<select name="coverMediaId"><option value="">不使用封面</option>${media.filter(x=>x.storagePath&&x.rightsStatus==='confirmed'&&x.matchStatus==='confirmed').map(x=>`<option value="${esc(x.id)}" ${d.coverMediaId===x.id?'selected':''}>${esc(x.name||x.id)}</option>`).join('')}</select><small>请先到媒体素材上传并审核图片</small></label><label>发布后状态<select name="status"><option value="active">上架</option><option value="offline" ${row?.status==='offline'?'selected':''}>下架</option></select></label></div><p>保存仅更新草稿；发布后 H5 与小程序读取同一版本。</p><div role="alert" id="editor-error"></div><div class="actions"><button class="btn primary">保存草稿</button></div></form></section></div>`;
}
function localTime(v){const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function values(kind,form,row){const data={...(row?.data||{}),...Object.fromEntries(new FormData(form))};for(const [key,,type]of schemas[kind]){if(type==='number')data[key]=Number(data[key]);if(type==='datetime-local')data[key]=data[key]?new Date(data[key]).toISOString():'';}if(kind==='banners')data.placement='home';if(!data.coverMediaId){delete data.cover;delete data.mediaApproval;}return data;}
