import test from 'node:test';
import assert from 'node:assert/strict';
import { database, referenceCatalog } from './helpers.mjs';
import { ContentService } from '../packages/core/content-service.mjs';
import { AssistantService } from '../packages/core/assistant-service.mjs';

test('AI assistant is fail-closed when no provider is configured',async t=>{const{db,repo,config}=await database();t.after(()=>db.close());const content=new ContentService(db,repo);await content.importCatalog(await referenceCatalog(),{publish:true});const assistant=new AssistantService(db,content,config);assert.equal(assistant.status().configured,false);await assert.rejects(()=>assistant.ask('admin','查缺图'),e=>e.code==='MODEL_NOT_CONFIGURED');});

test('AI assistant queries real records, persists proposal, requires confirmation and never auto-publishes',async t=>{
 const{db,repo,config}=await database();t.after(()=>db.close());const content=new ContentService(db,repo);await content.importCatalog(await referenceCatalog(),{publish:true});config.aiProvider='deepseek';config.aiModel='test-model';config.aiApiKey='test-key';config.aiBaseUrl='https://model.invalid/chat';let calls=0;
 const transport=async(_url,opts)=>{calls++;const req=JSON.parse(opts.body),messages=req.messages;if(calls===1)return Response.json({choices:[{message:{role:'assistant',content:'',tool_calls:[{id:'tool-1',type:'function',function:{name:'query_records',arguments:JSON.stringify({kind:'pois',search:'清晖阁'})}}]}}]});if(calls===2){const tool=JSON.parse(messages.at(-1).content);const record=tool.items[0];return Response.json({choices:[{message:{role:'assistant',content:'',tool_calls:[{id:'tool-2',type:'function',function:{name:'propose_change',arguments:JSON.stringify({kind:'pois',recordId:record.recordId,patchJson:JSON.stringify({description:'AI联调建议介绍'}),reason:'根据运营指令优化介绍'})}}]}}]});}return Response.json({choices:[{message:{role:'assistant',content:'已生成一条待确认提案，没有发布。'}}]});};
 const assistant=new AssistantService(db,content,config,transport);const before=(await repo.catalog()).pois.find(x=>x.id==='qinghui-pavilion').description;const result=await assistant.ask('admin-user','优化清晖阁介绍，联系电话13900009999');assert.equal(result.proposals.length,1);assert.equal((await repo.catalog()).pois.find(x=>x.id==='qinghui-pavilion').description,before);const tasks=await db.query('SELECT prompt_redacted,status FROM ai_tasks');assert.match(tasks[0].prompt_redacted,/\[手机号已脱敏\]/);assert.equal(tasks[0].status,'completed');await assert.rejects(()=>assistant.apply('admin-user',result.proposals[0].id,false),e=>e.code==='CONFIRMATION_REQUIRED');const applied=await assistant.apply('admin-user',result.proposals[0].id,true);assert.equal(applied.savedAsDraft,true);assert.equal((await repo.catalog()).pois.find(x=>x.id==='qinghui-pavilion').description,before);const draft=await content.get('pois','qinghui-pavilion');assert.equal(draft.data.description,'AI联调建议介绍');const pub=await content.publish({actorUserId:'admin-user'});assert.equal(pub.catalog.pois.find(x=>x.id==='qinghui-pavilion').description,'AI联调建议介绍');
});
