import './generate-types.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { compileNativeStyle } from '../packages/design/render.mjs';
import { validateCatalog } from '../packages/contracts/index.mjs';
const root = process.cwd();
const read = async (p) => JSON.parse(await fs.readFile(path.join(root, p), 'utf8'));
const catalog = validateCatalog(await read('packages/content/catalog.reference.json'));
const tokens = await read('packages/design/tokens.json');
const client = await read(process.env.CLIENT_CONFIG || 'deploy/client.example.json');
if (client.environment === 'production') {
    if (!/^wx[a-zA-Z0-9]{16}$/.test(client.appid) || !client.apiBaseUrl.startsWith('https://'))
        throw new Error('Production build requires the real WeChat AppID and HTTPS API origin');
}
const h5 = path.join(root, 'dist/h5'), admin = path.join(root, 'dist/admin'), weapp = path.join(root, 'apps/weapp/dist'), weappNative = path.join(root, 'dist/weapp-native');
for (const dir of [
    h5,
    admin,
    weapp,
    weappNative
])
    await fs.rm(dir, {
        recursive: true,
        force: true
    });
await fs.mkdir(h5, {
    recursive: true
});
await fs.cp('apps/h5/src', path.join(h5, 'src'), {
    recursive: true
});
await fs.cp('apps/h5/public', h5, {
    recursive: true
});
await fs.copyFile('apps/h5/index.html', path.join(h5, 'index.html'));

await fs.mkdir(admin,{recursive:true});
await fs.cp('apps/admin/src',path.join(admin,'src'),{recursive:true});
await fs.copyFile('apps/admin/index.html',path.join(admin,'index.html'));
await fs.cp('apps/weapp-native',weappNative,{recursive:true});

await fs.mkdir(path.join(h5, 'shared'), {
    recursive: true
});
await fs.copyFile('packages/client-core/index.mjs', path.join(h5, 'shared/client-core.mjs'));
const css = Object.entries(tokens).map(([k, v]) => `  --${k}: ${typeof v === 'number' ? v + 'px' : v};`).join('\n');
await fs.writeFile(path.join(h5, 'tokens.css'), `:root {\n${css}\n}\n`);
await fs.cp('apps/weapp/src', weapp, {
    recursive: true
});
await fs.mkdir(path.join(weapp, 'shared'), {
    recursive: true
});
const shared = await fs.readFile('packages/client-core/index.mjs', 'utf8');
const exports = [
    ...shared.matchAll(/^export\s+(?:function|const)\s+(\w+)/gm)
].map(x => x[1]);
if (!exports.length || /^import\s/m.test(shared) || /export\s+default/.test(shared))
    throw new Error('Shared source must be pure named exports');
await fs.writeFile(path.join(weapp, 'shared/client-core.js'), `// Generated by scripts/build.mjs. Do not edit.\n${shared.replace(/^export\s+/gm, '')}\nmodule.exports = { ${exports.join(', ')} };\n`);
await fs.writeFile(path.join(weapp, 'shared/config.js'), `// Public client settings only; never put IVY or WeChat secrets here.\nmodule.exports = ${JSON.stringify({
    apiBaseUrl: client.apiBaseUrl,
    environment: client.environment
}, null, 2)};\n`);
async function compileStyles(dir) {
    for (const e of await fs.readdir(dir, {
        withFileTypes: true
    })) {
        const p = path.join(dir, e.name);
        if (e.isDirectory())
            await compileStyles(p);
        else if (p.endsWith('.wxss'))
            await fs.writeFile(p, compileNativeStyle(await fs.readFile(p, 'utf8'), tokens));
    }
}
await compileStyles(weapp);
const appJson = JSON.parse(await fs.readFile(path.join(weapp, 'app.json'), 'utf8'));
appJson.window.navigationBarBackgroundColor = tokens.background;
appJson.window.backgroundColor = tokens.background;
await fs.writeFile(path.join(weapp, 'app.json'), JSON.stringify(appJson, null, 2) + '\n');
const project = {
    appid: client.appid,
    projectname: 'nanchong-city-tour',
    description: 'Native mini-program; canonical content served by shared API',
    compileType: 'miniprogram',
    miniprogramRoot: 'dist/',
    setting: {
        es6: true,
        enhance: true,
        minified: false,
        urlCheck: client.environment === 'production'
    },
    packOptions: {
        ignore: []
    }
};
await fs.writeFile('apps/weapp/project.config.json', JSON.stringify(project, null, 2) + '\n');
const manifest = {
    version: '4.4.0-rc.1',
    contentVersion: catalog.version,
    sharedSha256: createHash('sha256').update(shared).digest('hex'),
    tokensSha256: createHash('sha256').update(JSON.stringify(tokens)).digest('hex'),
    clients: [
        'h5',
        'admin',
        'weapp-native'
    ],
    legacyClients: [
        'weapp'
    ],
    production: client.environment === 'production'
};
await fs.writeFile('dist/build-manifest.json', JSON.stringify(manifest, null, 2) + '\n');
console.log(JSON.stringify({
    build: 'passed',
    ...manifest
}));

