import fs from 'node:fs';
import { loadConfig, missingHttp, missingMqtt } from '../packages/core/config.mjs';
import { loadDriver } from '../packages/core/drivers.mjs';
import { openDatabase } from '../packages/storage/database.mjs';

const result={status:'blocked',checks:[],mustBeRunAfterCredentials:['supplier IVY HTTP/MQTT replay','official WeChat preview with upload key/IP whitelist','iOS + Android physical-device acceptance','on-route field acceptance']};
const pass=(name,detail)=>result.checks.push({name,status:'passed',...(detail?{detail}: {})});
const block=(name,reason)=>result.checks.push({name,status:'blocked',reason:String(reason)});
const checkSync=(name,fn)=>{try{const detail=fn();pass(name,detail);}catch(e){block(name,e.message);}};
const readJson=file=>JSON.parse(fs.readFileSync(file,'utf8'));

checkSync('production integration lock',()=>{const p='deploy/integrations/package-lock.json';if(!fs.existsSync(p))throw new Error('real npm-resolved production lock missing');const l=readJson(p);for(const name of ['pg','mqtt'])if(!l.packages?.['node_modules/'+name]?.integrity)throw new Error('missing locked driver integrity: '+name);return{pg:l.packages['node_modules/pg'].version,mqtt:l.packages['node_modules/mqtt'].version};});
checkSync('PostgreSQL 16 compatibility evidence',()=>{const p='audit/postgres/result.json';if(!fs.existsSync(p))throw new Error('PostgreSQL CI acceptance evidence missing');const r=readJson(p);if(r.status!=='passed'||r.driver!=='postgres'||r.counts?.nodes!==5||r.counts?.pois!==21||r.counts?.walks!==4||r.counts?.steps!==9||r.draftPublishIsolation!==true)throw new Error('PostgreSQL compatibility evidence incomplete');return{verifiedAt:r.verifiedAt,counts:r.counts};});
checkSync('official WeChat toolchain lock',()=>{const p='deploy/wechat-ci/package-lock.json';if(!fs.existsSync(p))throw new Error('miniprogram-ci lock missing');const l=readJson(p),pkg=l.packages?.['node_modules/miniprogram-ci'];if(!pkg?.integrity||pkg.version!=='2.1.31')throw new Error('official miniprogram-ci 2.1.31 is not integrity-locked');return{version:pkg.version,note:'isolated build tool; audit evidence is retained separately'};});
checkSync('official WeChat preview evidence',()=>{const p='audit/wechat/preview-result.json';if(!fs.existsSync(p))throw new Error('real miniprogram-ci preview has not been run with AppID/upload key');const r=readJson(p);if(r.status!=='passed'||!fs.existsSync('audit/wechat/preview.jpg'))throw new Error('official preview evidence incomplete');return{completedAt:r.completedAt,appidSuffix:r.appidSuffix};});
checkSync('iOS + Android device evidence',()=>{const p='audit/wechat/device-acceptance.json';if(!fs.existsSync(p))throw new Error('physical-device evidence missing');const d=readJson(p);for(const platform of ['ios','android']){const x=d.devices?.[platform];if(x?.status!=='passed')throw new Error(platform+' not passed');for(const k of ['launch','wechatLogin','phoneAuthorization','contentRead','favoriteRoundTrip','supportRoundTrip','navigation','networkRetry'])if(x.checks?.[k]!==true)throw new Error(platform+' missing '+k);if(!Array.isArray(x.evidence)||!x.evidence.length)throw new Error(platform+' evidence missing');}return{verifiedAt:d.verifiedAt,version:d.version};});
for(const name of ['pg','mqtt'])checkSync(name+' runtime',()=>{loadDriver(name);return{name};});

let config=null;try{config=loadConfig();if(!config.production)throw new Error('NODE_ENV is not production');const missing=[...new Set([...missingHttp(config),...missingMqtt(config)])];if(missing.length)throw new Error('unconfigured IVY fields: '+missing.join(', '));if(!config.smsProviderConfigured)throw new Error('formal SMS gateway not configured');if(!(config.wechatAppId&&config.wechatAppSecret))throw new Error('WeChat AppID/AppSecret not configured');if(!(config.aiProvider&&config.aiModel&&config.aiApiKey))throw new Error('AI model/provider/key not configured');pass('production configuration',{smsProvider:config.smsProvider,aiProvider:config.aiProvider,aiModel:config.aiModel,wechatAppidSuffix:config.wechatAppId.slice(-6)});}catch(e){block('production configuration',e.message);}

if(config?.production&&result.checks.find(x=>x.name==='pg runtime')?.status==='passed'){
  let db;try{db=await openDatabase(config);await db.query('SELECT 1');const migrations=await db.query('SELECT version FROM schema_migrations ORDER BY version');const versions=migrations.map(x=>String(x.version));if(!versions.includes('005'))throw new Error('target database has not applied migration 005');pass('target PostgreSQL connection',{driver:db.driver,migrations:versions});const maxAge=Number(process.env.RELEASE_VERIFICATION_MAX_AGE_MS||7*86400000),cutoff=Date.now()-maxAge;for(const kind of ['ai','wechat','sms-delivery']){const rows=await db.query('SELECT provider,status,detail_json,created_at FROM integration_verifications WHERE integration=$1 AND status=$2 AND created_at>$3 ORDER BY created_at DESC LIMIT 1',[kind,'passed',cutoff]);if(!rows.length)block('live '+kind+' verification','no recent passed verification in target database');else pass('live '+kind+' verification',{provider:rows[0].provider,createdAt:Number(rows[0].created_at)});}}catch(e){block('target PostgreSQL connection',e.message);}finally{await db?.close().catch(()=>{});}
}

result.status=result.checks.every(x=>x.status==='passed')?'requires_supplier_and_field_acceptance':'blocked';
console.log(JSON.stringify(result,null,2));process.exitCode=result.status==='blocked'?2:0;

